# Generated by Django 3.2 on 2023-04-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
