# Generated by Django 3.2 on 2023-05-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_track_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('track_number',)},
        ),
    ]
